vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        article: 
            uri_prefix: /uploads/images/article
            upload_destination: '%kernel.project_dir%/public/uploads/images/article' 
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        article_source: 
            uri_prefix: /uploads/files/article
            upload_destination: '%kernel.project_dir%/public/uploads/files/article'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           

        vaccine: 
            uri_prefix: /uploads/images/vaccine
            upload_destination: '%kernel.project_dir%/public/uploads/images/vaccine' 
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    